lang: fr_FR
title: hl2
email: contact@hl2.com
description: >-
  hl2 est une start-up dédiée à l'Internet des Objets industriel,
  utilisant les nouvelles technologies LPWAN comme Sigfox™ et LoRaWAN™
baseurl: ""
url: https://hl2.com

social:
  name: hl2
  links:
    - https://twitter.com/hl2_fr
    - https://www.facebook.com/hl2group
    - https://www.linkedin.com/company/25071905
    - https://github.com/hl2

google:
  tag_manager:
    container_id: GTM-55HF8C3

twitter:
  username: hl2_fr

github:
  username:  hl2

linkedin:
  username: hl2-group

assets:
  precompile:
    - hl2.png
  raw_precompile:
    - src: posts/*.jpg
      dst: posts
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

# Build settings
markdown: kramdown
sass:
    style: compressed
    sass_dir: _assets/

plugins:
  - bootstrap
  - font-awesome-sass
  - autoprefixer-rails
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-google-tag-manager

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/hl2-dd5bd4aa99c3bf8366ba295c77b512c52416595e67d769a00f7c1f72db76cbb0.png
        alt: hl2 logo
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      jumboTitle: Actualités

collections:
  events:
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title
  pages:
    output: true
    permalink: /:path

# Exclude from processing.
exclude:
  - vendor
  - .editorconfig
  - .gitignore
  - .travis.yml
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - _config.yml
